models/Jefes.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "jefes".
 *
 * @property int $id
 * @property int $jefe
 * @property int $vendedor
 *
 * @property Rrpps $jefe0
 * @property Rrpps $vendedor0
 */
class Jefes extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    
    /*
     * Variables necesarias para campos de tablas relacionadas y calculados
     */
    public $nomjefe;
    public $nomrrpp;
    public $integrantes;
    public $tipo; //Tipo hace referencia a su rol (jefe o vendedor)
    public $telefono;

    public static function tableName()
    {
        return 'jefes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['jefe', 'vendedor'], 'required'],
            [['jefe', 'vendedor'], 'integer'],
            [['jefe', 'vendedor'], 'unique', 'targetAttribute' => ['jefe', 'vendedor'], 'message'=>'Ya existe esta combinación de jefe y vendedor.'],
            [['vendedor'], 'unique', 'message'=>'Este {attribute} ya está en un grupo. Para asignarle uno nuevo, eliminelo del anterior primero.'],
            [['vendedor'], 'exist', 'skipOnError' => true, 'targetClass' => Rrpps::className(), 'targetAttribute' => ['vendedor' => 'id']],
            [['jefe'], 'exist', 'skipOnError' => true, 'targetClass' => Rrpps::className(), 'targetAttribute' => ['jefe' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'jefe' => 'Jefe',
            'vendedor' => 'Vendedor',
            'nomjefe' => 'Jefe',
            'nomrrpp' => 'RRPP',
            'tipo' => 'Tipo',
            'telefono' => 'Teléfono',
        ];
    }

    /**
     * Gets query for [[Jefe0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJefe0()
    {
        return $this->hasOne(Rrpps::className(), ['id' => 'jefe']);
    }

    /**
     * Gets query for [[Vendedor0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getVendedor0()
    {
        return $this->hasOne(Rrpps::className(), ['id' => 'vendedor']);
    }
    
    public function getdropdownRrpps(){
        
        /*
         * Devuelve todos los rrpps a excepcion del -1 que esta reservado para el sistema
         * en un menu desplegable utilizado en los formularios
         */
        
        $models = Rrpps::find()->asArray()->select(['id, concat(nombre, " ", apellidos) nombre'])->where('id <> -1')->orderBy('nombre asc, apellidos asc')->all();
        return ArrayHelper::map($models, 'id', 'nombre');
        
    }
    
    public function getdropdownJefes(){
        
        /*
         * Devuelve todos los jefes (rrpps cuyo jefe es el -1 que hace referencia al sistema)
         * en un menu desplegable utilizado en los formularios
         */
        
        $models = Rrpps::find()->asArray()->select(['rrpps.id, concat(nombre, " ", apellidos) nombre'])->where('jefes.jefe = -1')->innerJoinWith('jefes')->orderBy('nombre asc, apellidos asc')->all();
        return ArrayHelper::map($models, 'id', 'nombre');
        
    }
}

controllers/JefesController.php
<?php

namespace app\controllers;

use app\models\Jefes;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * JefesController implements the CRUD actions for Jefes model.
 */
class JefesController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Jefes models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Jefes::find()->innerJoinWith('jefe0')->innerJoinWith('vendedor0')
                ->select(['jefes.id, jefe, vendedor, (select concat(rrpps.nombre, " ", rrpps.apellidos) from rrpps where jefe = rrpps.id) nomjefe, (select concat(rrpps.nombre, " ", rrpps.apellidos) from rrpps where vendedor = rrpps.id) nomrrpp']),
            
            'sort' => ['attributes' => ['nomjefe','nomrrpp']],
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionIndex2($jefe)
    {
        /*
         * Muestra los rrpp dados de alta en un grupo cuyo jefe es recibido como parametro
         */
        $dataProvider = new ActiveDataProvider([
            'query' => Jefes::find()->innerJoinWith('jefe0')->innerJoinWith('vendedor0')->where("jefes.jefe = $jefe")
                ->select(['jefes.id, jefe, vendedor, (select concat(rrpps.nombre, " ", rrpps.apellidos) from rrpps where jefe = rrpps.id) nomjefe, (select concat(rrpps.nombre, " ", rrpps.apellidos) from rrpps where vendedor = rrpps.id) nomrrpp']),
            
            'sort' => ['attributes' => ['nomjefe','nomrrpp']],
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index2', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Jefes model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->actionRelacionar($id)
        ]);
    }
    
    private function actionRelacionar($id) {
        /*
        * Obtiene valores de sus tablas relacionadas y se lo asigna al modelo. Tambien formatea campos como las fechas y horas
        */
        $model = $this->findModel($id);
        $model->nomjefe = $model->jefe0->nombre .' ' . $model->jefe0->apellidos;
        $model->nomrrpp = $model->vendedor0->nombre .' ' . $model->vendedor0->apellidos;
        return $model;
    }

    /**
     * Creates a new Jefes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate($jefe)
    {
        /*
         * Permite agregar un rrpp a un grupo cuyo jefe es recibido como parametro
         */
        $model = new Jefes();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                $model->jefe = $jefe;
                return $this->redirect(['index2', 'jefe' => $model->jefe, 'nomjefe' => $model->nomjefe]);
            }
        } else {
            $model->loadDefaultValues();
            $model->jefe = $jefe;
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    public function actionCreategrupo()
    {
        /*
         * Asigna un rrpp a el grupo del jefe -1 que es el sistema de lixet. Los rrpps que esten en este grupo seran jefes
         */
        $model = new Jefes();       
        $model->jefe = -1;
        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues(); 
        }
        
        return $this->render('creategrupo', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Jefes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Jefes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['grupo']);
    }

    /**
     * Finds the Jefes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Jefes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Jefes::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionGrupo() {
        /*
         * Muestra los grupos de rrpp agrupados por jefes cuando estos jefes estan en el grupo del sistema lixet.
         */
        $dataProvider = new ActiveDataProvider([
            'query' => Jefes::find()->innerJoinWith('vendedor0')
                ->groupBy('vendedor')
                ->select(['vendedor jefe, concat(rrpps.nombre, " ", rrpps.apellidos) nomjefe, vendedor jefaso, (SELECT count(*) FROM jefes WHERE jefe = jefaso) integrantes'])
                ->where('jefe = -1'),
        ]);

        return $this->render('grupos', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionMigrupo() {
        /*
        *  Devuelve el grupo al que pertenece el usuario que esta navegando en el sistema
        */
        $union = "SELECT 'RRPP' tipo, vendedor, rrpps.telefono, (select concat(rrpps.nombre, ' ', rrpps.apellidos) from rrpps where vendedor = rrpps.id) as nomrrpp FROM jefes INNER JOIN rrpps on jefes.vendedor = rrpps.id WHERE jefe = (SELECT jefe FROM jefes WHERE vendedor = (SELECT IdRRPP FROM User WHERE Id = " . \Yii::$app->user->identity->id . "))";
        $dataProvider = new ActiveDataProvider([
            'query' => Jefes::find()->innerJoinWith('jefe0')//->innerJoinWith('vendedor0')//->groupBy('jefe')
                ->select(['"Jefe" tipo, jefe, rrpps.telefono, concat(rrpps.nombre, " ", rrpps.apellidos) as nomrrpp'])
                ->where("jefe = (SELECT jefe FROM jefes WHERE vendedor = (SELECT IdRRPP FROM User WHERE Id =" . \Yii::$app->user->identity->id ."))")
                ->union($union),
            'sort' => ['attributes' => ['id','vendedor','nomrrpp','tipo','telefono']],
        ]);

        return $this->render('migrupo', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionJefes()
    {
        /*
         * Muestra el grupo de los jefes de rrpp que esten en grupo del sistema lixet.
         */
        $dataProvider = new ActiveDataProvider([
            'query' => Jefes::find()->innerJoinWith('vendedor0')
                ->select(['jefes.id, (select concat(rrpps.nombre, " ", rrpps.apellidos) from rrpps where vendedor = rrpps.id) nomjefe'])
                ->where('jefe=-1'),
            
            'sort' => ['attributes' => ['nomjefe']],
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('jefes', [
            'dataProvider' => $dataProvider,
        ]);
    }
}

views/jefes/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Jefes */
/* @var $form yii\widgets\ActiveForm */

/*
 * 
 * Formulario para asignar un RRPP a un grupo
 * 
 */
?>

<div class="jefes-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'jefe')->dropDownList($model->getdropdownJefes(),['disabled' => false]) ?>

    <?= $form->field($model, 'vendedor')->dropDownList($model->getdropdownRrpps()) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-lxt']) ?>
    </div>
    
    <?php ActiveForm::end(); ?>

</div>

views/jefes/_form2.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Jefes */
/* @var $form yii\widgets\ActiveForm */

//$model->jefe = -1

/*
 * 
 *      Formulario para crear un nuevo jefe de grupo
 * 
 */

?>

<div class="jefes-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="d-none">
        <?= $form->field($model, 'jefe')->dropDownList($model->getdropdownJefes(),['prompt' => '','disabled' => 'disabled']) ?>
    </div>  
    <?= $form->field($model,'vendedor')->dropDownList($model->getdropdownRrpps(),['prompt' => '']) ?>
    
    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-lxt']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/jefes/_grupo.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
//$clave = $model->id;

/*
 * 
 * Vista que permite ver un jefe de grupo y la cantidad de vendedores a su cargo
 * 
 */
?>

<div class="card sombrabox" style="margin-top: 10px; margin-bottom: 20px">
    <div class="card-body">
        
        <div class="caption text-center">
            <h4><?= $model->nomjefe ?></h4>
            <h6><?= $model->integrantes ?> integrantes</h6>
            <?= Html::a('Administrar', ['/jefes/index2','jefe'=>$model->jefe, 'nomjefe' => $model->nomjefe], ['class' => 'btn btn-lxt sombrabox']) ?>
        </div>

    </div>
</div> 

views/jefes/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Jefes */

/*
 * 
 * Vista para asignar un rrpp a un grupo
 * 
 */

// Obtiene como parametro el jefe del grupo
$nomjefe = Yii::$app->getRequest()->getQueryParam('nomjefe');
$jefe = Yii::$app->getRequest()->getQueryParam('jefe');

$this->params['breadcrumbs'][] = ['label' => 'Grupos', 'url' => ['grupo']];

// Si el parametro del nombre esta vacio muestra enlace para volver al grupo del usuario, en su defecto muestra el grupo del jefe
if(isset($nomjefe)){
    $this->title = 'Asignar RRPP a ' . $nomjefe;
    $this->params['breadcrumbs'][] = ['label' => 'Grupo de ' . $nomjefe, 'url' => ['index2', 'jefe' => $jefe, 'nomjefe' => $nomjefe]];
} else {
    $this->title = 'Asignar RRPP';
    $this->params['breadcrumbs'][] = ['label' => 'Mi Grupo', 'url' => ['migrupo']];
}

$this->params['breadcrumbs'][] = $this->title;

?>
<div class="jefes-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/jefes/creategrupo.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Jefes */

/*
 * 
 * Vista para crear un nuevo jefe de grupo
 * 
 */

$this->title = 'Asignar jefe de grupo';
$this->params['breadcrumbs'][] = ['label' => 'Grupos', 'url' => ['grupo']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jefes-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form2', [
        'model' => $model,
    ]) ?>

</div>

views/jefes/grupos.php
<?php
use yii\helpers\Html;
use yii\helpers\HTMLPurifier;
use circulon\widgets\ColumnListView;

/*
 * 
 *      Vista que muestra todos los jefes y la cantidad de vendedores a su cargo
 * 
 */
$titulo = "Grupos";
$this->title = $titulo;
$this->params['breadcrumbs'][] = $this->title;

// Se obtiene el rol del usuario registrado para mostrarle sus acciones permitidas
$rol = isset(array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]) ? array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]:'';
if($rol == "Admin"){
    // Si es administrador se le permite ver el grupo de jefes y crear un jefe nuevo
    $boton = Html::a('Crear jefe', ['/jefes/creategrupo',], ['class' => 'btn btn-lxt sombrabox']);
    $boton2 = Html::a('Jefes', ['/jefes/jefes',], ['class' => 'btn btn-lxt sombrabox']);
} else {
    $boton = "";
    $boton2 = "";
}

?>

<div class="well well-sm text-center">
    <h1 style="">
        <?=$titulo?>
    </h1>
</div>

<p>
    <?= $boton ?> <?= $boton2 ?>
</p>

<div class="">
    <?= ColumnListView::widget([ 
        'dataProvider' => $dataProvider,
        'itemView' => '_grupo',
        'layout'=> "\n{pager}\n{items}",
        'columns' => 2,
    ]);
    ?>
</div>

views/jefes/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */


/*
 * 
 * Vista principal de todos los vendedores que esten en grupos y sus jefes
 * 
 */

$key = Yii::$app->getRequest()->getQueryParam('jefe');
$this->title = 'Grupo';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jefes-index">
    
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Agregar RRPP', ['create','jefe' => $key], ['class' => 'btn btn-lxt']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md'],
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'jefe',
            //'vendedor',
            'nomjefe',
            'nomrrpp',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/jefes/index2.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*
 * 
 * Vista que muestra todos los integrantes de un grupo
 * 
 */

$key = Yii::$app->getRequest()->getQueryParam('jefe');
$nomjefe = Yii::$app->getRequest()->getQueryParam('nomjefe');
$this->title = isset($nomjefe) ?  'Grupo de ' . $nomjefe : 'Grupo';
$this->params['breadcrumbs'][] = ['label' => 'Grupos', 'url' => ['jefes/grupo']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="jefes-index">
    
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Agregar RRPP', ['create','jefe' => $key, 'nomjefe'=>$nomjefe], ['class' => 'btn btn-lxt']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md'],
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'jefe',
            //'vendedor',
            'nomjefe',
            'nomrrpp',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/jefes/jefes.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */


/*
 * 
 *      Vista que muestra todos los jefes de grupo
 * 
 */

$key = Yii::$app->getRequest()->getQueryParam('jefe');
$this->title = 'Jefes';

$this->params['breadcrumbs'][] = ['label' => 'Grupos', 'url' => ['jefes/grupo']];
$this->params['breadcrumbs'][] = $this->title;

// Se obtiene el rol del usuario registrado para mostrarle sus acciones permitidas
$rol = isset(array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]) ? array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]:'';
if($rol == "Admin"){
    // Si es admin se le permite crear un jefe
    $boton = Html::a('Crear jefe', ['/jefes/creategrupo',], ['class' => 'btn btn-lxt sombrabox']);
} else {
    $boton = "";
}

?>
<div class="jefes-index">
    
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= $boton ?> 
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md'],
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'jefe',
            //'vendedor',
            'nomjefe',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/jefes/migrupo.php
<?php
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*
 * 
 *  Vista que muestra los integrantes del grupo al que pertenece el usuario registrado
 * 
 */

$titulo = 'Mi Grupo';
$this->title = $titulo;
$this->params['breadcrumbs'][] = $this->title;
//$nombre = Yii::$app->user->identity->idrrpp0->nombre . " " . Yii::$app->user->identity->idrrpp0->apellidos;

// Obtiene el nombre y apellidos para mostrarlo
$nombre = isset(Yii::$app->user->identity->idrrpp0->nombre) ? Yii::$app->user->identity->idrrpp0->nombre:"";
$nombre = isset(Yii::$app->user->identity->idrrpp0->apellidos) ?  $nombre . " " . Yii::$app->user->identity->idrrpp0->apellidos:$nombre;

// Se obtiene el rol del usuario registrado para mostrarle sus acciones permitidas
$rol = isset(array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]) ? array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]:'';
$idrrpp = Yii::$app->user->identity->idrrpp;

if($rol == "Admin" or $rol == "Jefe"){
    // Si es administrador o jefe se le permite crear, ver, actualizar y borrar
    $boton = Html::a('Agregar RRPP', ['/jefes/create','jefe'=>$idrrpp,'nomjefe'=>$nombre], ['class' => 'btn btn-lxt sombrabox']);
    $actioncolumn = [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ];
} else {
    $boton = "";
    $actioncolumn = [];
}

?>
<div class="well well-sm text-center">
    <h1 style="">
        <?= $titulo ?>
    </h1>
</div>

<p>
    <?= $boton ?>
</p>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md'],
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],
            'tipo',
            'nomrrpp',
            'telefono',
        ],
    ]); ?>

views/jefes/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Jefes */

$this->title = 'Actualizar ' . $model->vendedor0->nombre . " " . $model->vendedor0->apellidos . ' en el grupo de ' . $model->jefe0->nombre . " " . $model->jefe0->apellidos;
//$this->params['breadcrumbs'][] = ['label' => 'Grupos', 'url' => ['grupo']];
//$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = ['label' => 'Grupos', 'url' => ['grupo']];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="jefes-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/jefes/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Jefes */

/*
 * 
 *      Vista detallada de un vendedor y su jefe
 * 
 */

$this->title = $model->nomjefe == $model->nomrrpp ? 'Jefe: ' . $model->nomjefe : $model->nomjefe . ' - ' . $model->nomrrpp;
$this->params['breadcrumbs'][] = ['label' => 'Grupos', 'url' => ['grupo']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="jefes-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-lxt']) ?>
        <?= Html::a('Borrar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Estas seguro de querer borrar este registro?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'options' => ['class' => 'table table-hover table-responsive-md'],
        'attributes' => [
            //'id',
            'nomjefe',
            'nomrrpp',
        ],
    ]) ?>

</div>