controllers/EventosController.php
<?php

namespace app\controllers;

use app\models\Eventos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * EventosController implements the CRUD actions for Eventos model.
 */
class EventosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Eventos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Eventos::find()//->orderBy('id desc'),
            /*
            'pagination' => [
                'pageSize' => 50
            ],*/
            ,'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Eventos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Eventos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    /*public function uploadPath() {
        return Url::to('@web/img/');
    }*/
    
    public function upload($fil){
        /*
         * Permite subir una imagen de portada del evento
         */
        $var = 'img/eventos/' . $this->request->bodyParams["Eventos"]["codigo"];
        if ($fil) {
            $this->deleteFile($this->request->bodyParams["Eventos"]["codigo"], '');
            foreach ($fil as $file) {
                $file->saveAs($var .'.'. $file->extension);
            }   
        }
    }
    
    public function uploadHeader($fil) {
        /*
         * Permite subir una imagen de cabecera del evento
         */
        $var = 'img/eventos/' . $this->request->bodyParams["Eventos"]["codigo"]. '-home';
        if ($fil) {
            $this->deleteFile($this->request->bodyParams["Eventos"]["codigo"], '-home');
            foreach ($fil as $file) {
                $file->saveAs($var .'.'. $file->extension);
            }   
        }
    }
    
    public function deleteFile($code, $position) {
        /*
        * No usar (Incompleto) - Borra una imagen recibida como parametro
        */
        $img = getcwd() . '/img/eventos/' . $code;
        if($position != ''){
            $img = $img . $position;
        }
        
        //if(file_exists($img . '.jpg') || fileExists($img . '.png')){
          //unlink(Yii::getAlias('@root') . '/img/eventos/'. $img . '.jpg');
          //unlink($img . '.jpg');
          //unlink($img . '.png');
        //} 
    }

    public function actionCreate()
    {
        $model = new Eventos();
        
        if ($this->request->isPost) {
            // Agrega al modelo los archivos subidos en el formulario
            $model->file = UploadedFile::getInstances($model, 'file');
            $model->filemain = UploadedFile::getInstances($model, 'filemain');
            // Sube los archivos del modelo a web/img/eventos
            $this->upload($model->file, $model->filemain);
            $this->uploadHeader($model->filemain);
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    public function actionCreatebak()
    {
        /*
         * Copia de seguridad de actionCreate
         */
        $model = new Eventos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Eventos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            // Agrega al modelo los archivos subidos en el formulario
            $model->file = UploadedFile::getInstances($model, 'file');
            $model->filemain = UploadedFile::getInstances($model, 'filemain');
            // Sube los archivos del modelo a web/img/eventos
            $this->upload($model->file, $model->filemain);
            $this->uploadHeader($model->filemain);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Eventos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Eventos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Eventos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function findModel($id)
    {
        if (($model = Eventos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    /*public function actionUpload($id){
        $model = $this->findModel($id);
        if(Yii::$app->request->ispost){
            $model->imagen = UploadedFile::getInstance($model, 'imagen');
            if($model->upload()) {
                return $this->redirect(['view', 'id' => $model->id]);
                $model->up
            }
        }
        return $this->render('upload', ['model' => $model]);
    }*/
    
    public function actionMiseventos()
    {
        /*
        *  Devuelve los eventos en los que este contratado el usuario que esta utilizando el sistema
        */
        $dataProvider = new ActiveDataProvider([
            'query' => Eventos::find()
                //->innerJoinWith('contratos')
                ->leftJoin('contratos', 'contratos.evento = eventos.id')
                //->leftJoin('alquileres', $on = 'eventos.id = alquileres.evento')
                ->select('eventos.id, eventos.codigo, eventos.edicion, eventos.nombre, eventos.tipo')
                ->where("contratos.rrpp = (SELECT IdRRPP FROM User WHERE Id =" . \Yii::$app->user->identity->id .")")
                ,
            
            /*'pagination' => [
                'pageSize' => 50
            ],
            */
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            
        ]);

        return $this->render('miseventos', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
}

controllers/RrppsController.php
<?php

namespace app\controllers;

use app\models\Rrpps;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RrppsController implements the CRUD actions for Rrpps model.
 */
class RrppsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Rrpps models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Rrpps::find()->where('id <> -1')
                ->select(['id, dni, concat(nombre, " ", apellidos) nombre, telefono, email, '
                    . 'DATE_FORMAT(f_nacimiento, "%d-%m-%Y") f_nacimiento']),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rrpps model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->actionFormatofechas($id),
        ]);
    }
    
    //Dar formato a las fechas
    private function actionFormatofechas($id) {
        /*
         * Devuelve un modelo con las fechas formateadas
         */
        $model = $this->findModel($id);
        $date = new \DateTime($model->f_nacimiento);
        $model->f_nacimiento = $date->format('d/m/Y');
        return $model;
    }
    
    /**
     * Creates a new Rrpps model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Rrpps();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Rrpps model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Rrpps model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rrpps model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Rrpps the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rrpps::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La página solicitada no existe.');
    }
    
    //Obtener todos los rrpps activos en un evento y sus entradas
    public function actionRrpps($evento) {
        
        //Consulta sql para obtener tambien los rrpps que no esten activos en el evento pero tengan entradas de este
        $sql = "select rrpps.id, rrpps.nombre, rrpps.apellidos, entradas.evento evento,count(*) numentradas
            from rrpps 
            inner join entradas on entradas.vendedor = rrpps.id 
            where rrpps.id <> -1 and entradas.evento = $evento
            group by rrpps.id";
        
        //RRPPS dados de alta en el evento pasado como parametro y entradas que tienen asignadas
        $dataProvider = new ActiveDataProvider([
            'query' => Rrpps::find()
                ->innerJoinWith("contratos")
                ->where("rrpps.id <> -1 and contratos.evento = $evento")
                ->select(["rrpps.id, rrpps.nombre, rrpps.apellidos, contratos.evento evento,"
                    . "(select count(*)from entradas where entradas.evento = $evento and entradas.vendedor = rrpps.id) numentradas"])
                ->union($sql)
        ]);
        
        return $this->render("Rrpps",[
            "dataProvider" => $dataProvider,
        ]);
    }
    
}

views/entradas/crearentrada.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

/*
 * 
 *      Vista para generar entradas desde un evento
 * 
 */

// Recibe el nombre del evento del parametro del controlador
$nomevento = Yii::$app->getRequest()->getQueryParam('nomevento');
$this->title = 'Generar entrada de ' . $nomevento;

$this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
$this->params['breadcrumbs'][] = ['label' => $nomevento, 'url' => ['eventos/view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['indexfromeventos', 'evento' => $model->evento, 'nomevento' => $nomevento]];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="entradas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formcrearentrada', [
        'model' => $model,
    ]) ?>

</div>

views/entradas/entradasrrpp.php
<?php
use yii\helpers\Html;
use yii\helpers\HTMLPurifier;
use circulon\widgets\ColumnListView;

/*
 * 
 *      Vista para mostrar las entradas asignadas a un RRPP en un evento
 * 
 */

// Recibe los parametros enviados al controlador
$nomvendedor = Yii::$app->getRequest()->getQueryParam('nomrrpp');
$nomevento = Yii::$app->getRequest()->getQueryParam('nomevento');
$rrpp = Yii::$app->getRequest()->getQueryParam('rrpp');
$evento = Yii::$app->getRequest()->getQueryParam('evento');

$titulo = "Entradas de " . $nomvendedor . " en " . $nomevento;
$this->title = $titulo;
$this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
$this->params['breadcrumbs'][] = ['label' => $nomevento, 'url' => ['eventos/view', 'id' => $evento]];
$this->params['breadcrumbs'][] = ['label' => 'RRPPS', 'url' => ['rrpps/rrpps', 'evento' => $evento, 'nomevento' => $nomevento]];
$this->params['breadcrumbs'][] = $nomvendedor;
?>

<div class="well well-sm text-center">
    <h2 style="">
        <?=$titulo?>
    </h2>
</div>

<p>
    <?= Html::a('Asignar entradas', ['/entradas/asignarentradas', 'evento' => $evento, 'rrpp' => $rrpp, 'nomevento' => $nomevento, 'nomrrpp' => $nomvendedor], ['class' => 'btn btn-lxt sombrabox']) ?>
</p>

<div class="">
    <?= ColumnListView::widget([ 
        'dataProvider' => $dataProvider,
        'itemView' => '_entradarrpp',
        'layout'=> "\n{pager}\n{items}",
        'columns' => 2,
    ]);
    ?>
</div>

views/entradas/indexfromeventos.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*
 * 
 *  Vista principal de las entradas de un evento
 * 
 */

// Se obtiene el rol del usuario registrado para mostrarle sus acciones permitidas
$nomevento = Yii::$app->getRequest()->getQueryParam('nomevento');
$evento = Yii::$app->getRequest()->getQueryParam('evento');

$this->title = 'Entradas';

// Migas de pan para volver al evento al que pertenece
$this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
$this->params['breadcrumbs'][] = ['label' => $nomevento, 'url' => ['eventos/view', 'id' => $evento]];
$this->params['breadcrumbs'][] = $this->title;
$this->title = $this->title . '  '. $nomevento;

// Se obtiene el rol del usuario registrado para mostrarle sus acciones permitidas
$rol = isset(array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]) ? array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]:'';
$permiso=0;
$crear = "";
// Por defecto solo se permite ir a las entradas que tenga asignado el usuario
$actioncolumn = [
                'header' => '',
                'content' => function($model) {
                    return Html::a('Mis Entradas',['misentradas'], ['class' => 'btn btn-lxt']);
                }  
            ];
switch ($rol) {
    case "Admin":
        // Permisos totales
        $permiso = 4;
        $crear = Html::a('Crear entradas', ['generar','evento'=>$evento,'nomevento'=>$nomevento], ['class' => 'btn btn-lxt']);
        $actioncolumn = [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    if ($action == "view") {
                        return Url::to(['viewfromeventos', 'id' => $model->id]);
                    } else if ($action == "update"){
                         return Url::to(['updatefromeventos', 'id' => $model->id]);
                    } else if ($action == "delete"){
                         return Url::to(['deletefromeventos', 'id' => $model->id]);
                    }
                 }
            ];
        break;
    case "Jefe":
        $permiso = 3;
        // Ver sus entradas asignadas, vender la entrada de un RRPP o imprimir una entrada vendida
        $crear = Html::a('Mis entradas', ['entradas/misentradaseventos','evento'=> $evento,'nomevento'=>$nomevento], ['class' => 'btn btn-lxt']);
        $actioncolumn = [
                'header' => '',
                'content' => function($model) {
                    if($model->nomcomprador){
                        return Html::a('Imprimir',['report','id'=>$model->id], ['class' => 'btn btn-danger']);
                    } else {
                        return Html::a('Vender',['venderentrada','id'=>$model->id], ['class' => 'btn btn-lxt']);
                    }
                }  
            ];
        break;
    case "RRPP":
        $permiso = 2;
        break;
    case "Cliente":
        $permiso = 1;
        break;
}
?>
<div class="entradas-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= $crear ?>
    </p>


    <?= GridView::widget([
        
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md',],
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
        'columns' => [
            'nomevento',
            'numentrada',
            //'precio',
            [
                'label' => 'Precio',
                'attribute' =>'precio',
                'contentOptions' => ['class' => 'text-center'],
                'value'=>function ($model) {
                    return number_format($model->precio, 2, ',', '.') . "€";
                },
            ],
            'tipo',
            'nomvendedor',
            'nomcomprador',
            'fecha',
            $actioncolumn,
            
        ],
    ]); ?>


</div>

views/entradas/mejoresvendedores.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*
 *
 *      Vista para mostrar los mejores vendedores de la plataforma
 * 
 */

$this->title = 'Mejores Vendedores';
$this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entradas-index">

    <h1><?= Html::encode($this->title) ?></h1>

   <?= GridView::widget([
        
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md',],
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nomvendedor',
            'cantidad',
            //'comision',
            //'precio',
            //'beneficio',
            [
                'label' => 'Comisión',
                'attribute' =>'comision',
                'contentOptions' => ['class' => 'text-left'],
                'value'=>function ($model) {
                    return number_format($model->comision, 2, ',', '.') . "€";
                },
            ],
            [
                'label' => 'Precio',
                'attribute' =>'precio',
                'contentOptions' => ['class' => 'text-left'],
                'value'=>function ($model) {
                    return number_format($model->precio, 2, ',', '.') . "€";
                },
            ],
            [
                'label' => 'Beneficio',
                'attribute' =>'beneficio',
                'contentOptions' => ['class' => 'text-left'],
                'value'=>function ($model) {
                    return number_format($model->beneficio, 2, ',', '.') . "€";
                },
            ],
        ],
    ]); ?>


</div>

views/entradas/mejoresvendedoresevento.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*
 *
 *      Vista para mostrar los mejores vendedores de un evento
 * 
 */

// Se obtiene el rol del usuario registrado para mostrarle sus acciones permitidas
$nomevento = Yii::$app->getRequest()->getQueryParam('nomevento');
$evento = Yii::$app->getRequest()->getQueryParam('evento');

// Migas de pan para volver al evento al que pertenece
$this->title = 'Mejores Vendedores de ' . $nomevento;
$this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
$this->params['breadcrumbs'][] = ['label' => $nomevento, 'url' => ['eventos/view','id'=>$evento]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entradas-index">

    <h1><?= Html::encode($this->title)?></h1>
    <h5><?=$total?></h5>

   <?= GridView::widget([
        
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md',],
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nomvendedor',
            'cantidad',
            //'comision',
            //'precio',
            //'beneficio',
            [
                'label' => 'Comisión',
                'attribute' =>'comision',
                'contentOptions' => ['class' => 'text-left'],
                'value'=>function ($model) {
                    return number_format($model->comision, 2, ',', '.') . "€";
                },
            ],
            [
                'label' => 'Precio',
                'attribute' =>'precio',
                'contentOptions' => ['class' => 'text-left'],
                'value'=>function ($model) {
                    return number_format($model->precio, 2, ',', '.') . "€";
                },
            ],
            [
                'label' => 'Beneficio',
                'attribute' =>'beneficio',
                'contentOptions' => ['class' => 'text-left'],
                'value'=>function ($model) {
                    return number_format($model->beneficio, 2, ',', '.') . "€";
                },
            ],
        ],
    ]); ?>


</div>

views/entradas/updatefromentradasrrpp.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

/*
 * 
 *      Vista que permite asignar una entrada a un rrpp recibido como parametro
 * 
 */

$nomevento = $model->nomevento;
$evento = $model->evento;
// Obtiene los parametros del controlador
$nomrrpp = Yii::$app->getRequest()->getQueryParam('nomrrpp');
$rrpp = Yii::$app->getRequest()->getQueryParam('rrpp');

$this->title = $model->evento0->nombre .' '. $model->evento0->edicion . " - ". $model->numero;

// Migas de pan para volver al evento y al rrpp al que pertenece
$this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
$this->params['breadcrumbs'][] = ['label' => $nomevento, 'url' => ['eventos/view', 'id' => $evento]];
$this->params['breadcrumbs'][] = ['label' => 'RRPPS', 'url' => ['rrpps/rrpps', 'evento' => $evento, 'nomevento' => $nomevento]];
$this->params['breadcrumbs'][] = ['label' => $nomrrpp, 'url' => ['entradas/entradasrrpp', 'rrpp' => $rrpp, 'nomrrpp' => $nomrrpp, 'evento' => $evento, 'nomevento' => $nomevento]];
$this->params['breadcrumbs'][] = ['label' => 'Asignar entradas', 'url' => ['asignarentradas', 'rrpp' => $rrpp, 'nomrrpp' => $nomrrpp,
    'evento' => $evento, 'nomevento' => $nomevento]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entradas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_formcambiarvendedor', [
        'model' => $model,
    ]) ?>

</div>

views/entradas/venderentradaevento.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entradas */

/*
 * 
 *      Vista para vender una entrada desde un evento
 * 
 */

$nomevento = $model->nomevento;
$evento = $model->evento;

$this->title = $model->evento0->nombre .' '. $model->evento0->edicion . " - ". $model->numero;

// Obtenemos el rol para cambiar las migas de pan en funcion de las acciones permitidas del usuario
$rol = isset(array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]) ? array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]:'';
if($rol == "Jefe") {
    $this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
    $this->params['breadcrumbs'][] = ['label' => $nomevento, 'url' => ['eventos/view','id'=>$evento]];
    $this->params['breadcrumbs'][] = ['label' => 'Entradas', 'url' => ['entradas/indexfromeventos','evento' => $evento, 'nomevento' => $nomevento]]; 
} else {
    $this->params['breadcrumbs'][] = ['label' => 'Mis Entradas', 'url' => ['entradas/misentradaseventos','evento' => $evento, 'nomevento' => $nomevento]];
}

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entradas-update">

    <h1><?= Html::encode($this->title) ?></h1>
    
    <!--  Advertencia sobre la venta de una entrada -->
    <div class="col-md-12 bg-danger text-white mt-4 mb-4 pt-4 pl-4 pr-4 pb-2 h-auto cerrar">
        <span class="closebtn">&times;</span>  
        <p><b>Recuerda que al pulsar sobre el botón guardar se confirmará la transacción</b> y deberas recibir <?=number_format($model->precio, 2, ',', '.')?>€ por parte del cliente.
        <br>
        Recibirás <?=number_format($model->comision, 2, ',', '.')?>€ por parte del jefe de tu equipo de ventas dentro del plazo previamente acordado.
        <br>
        En caso de no haber seleccionado ningun comprador la transacción se considerará nula y no se realizaran cambios.
        </p>
    </div>   
    
    <!--  Codigo javascript para mostrar la advertencia -->
    <script>
        var close = document.getElementsByClassName("closebtn");
        var i;

        for (i = 0; i < close.length; i++) {
          close[i].onclick = function(){
            var div = this.parentElement;
            div.style.opacity = "0";
            setTimeout(function(){ div.style.display = "none"; }, 600);
          }
        }
    </script>
    

    <?= $this->render('_formvenderentrada', [
        'model' => $model,
    ]) ?>

</div>