models/Contratos.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "contratos".
 *
 * @property int $id
 * @property int $evento
 * @property int $rrpp
 *
 * @property Eventos $evento0
 * @property Rrpps $rrpp0
 */
class Contratos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    
    /*
     * Variables necesarias para campos de tablas relacionadas
     */
    public $nomrrpp;
    public $nomevento;
    public $codigo;
    
    public static function tableName()
    {
        return 'contratos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['evento', 'rrpp'], 'required'],
            [['evento', 'rrpp'], 'integer'],
            [['evento', 'rrpp'], 'unique', 'targetAttribute' => ['evento', 'rrpp']],
            [['evento'], 'exist', 'skipOnError' => true, 'targetClass' => Eventos::className(), 'targetAttribute' => ['evento' => 'id']],
            [['rrpp'], 'exist', 'skipOnError' => true, 'targetClass' => Rrpps::className(), 'targetAttribute' => ['rrpp' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'evento' => 'Evento',
            'rrpp' => 'RRPP',
            'nomrrpp' => 'RRPP',
            'nomevento' => 'Evento',
        ];
    }

    /**
     * Gets query for [[Evento0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEvento0()
    {
        return $this->hasOne(Eventos::className(), ['id' => 'evento']);
    }

    /**
     * Gets query for [[Rrpp0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRrpp0()
    {
        return $this->hasOne(Rrpps::className(), ['id' => 'rrpp']);
    }
    
    public function getdropdownEventos(){
        
        /*
         * Devuelve todos los eventos en un menu desplegable utilizado en los formularios
         */
        
        $models = Eventos::find()->asArray()->select(['id, concat(nombre, " (", codigo, "-", edicion, ")") nombre'])->orderBy('id desc')->all();
        return ArrayHelper::map($models, 'id', 'nombre');
       
    }
    
    public function getdropdownRrpps(){
        
        /*
         * Devuelve todos los rrpps a excepcion del -1 que esta reservado para el sistema
         * en un menu desplegable utilizado en los formularios
         */
        
        $models = Rrpps::find()->asArray()->select(['id, concat(nombre, " ", apellidos) nombre'])->where('id <> -1')->orderBy('nombre asc, apellidos asc')->all();
        return ArrayHelper::map($models, 'id', 'nombre');
        
    }
}

controllers/ContratosController.php
<?php

namespace app\controllers;

use app\models\Contratos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ContratosController implements the CRUD actions for Contratos model.
 */
class ContratosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Contratos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        /*
        * Muestra todos los Contratos y los datos relevantes de sus tablas. Elnombre y apellidos del rrpp los muestra concatenados
        */
        $dataProvider = new ActiveDataProvider([
            'query' => Contratos::find()->innerJoinWith('rrpp0')->innerJoinWith('evento0')
                ->select(['contratos.id id, eventos.nombre nomevento, rrpps.id rrpp, eventos.id evento, concat(rrpps.nombre,rrpps.apellidos) nomrrpp']),
            
            'sort' => ['attributes' => ['nomevento','nomrrpp']],
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Contratos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->actionRelacionar($id)
        ]);
    }
    
    public function actionViewfromevento($id)
    {
        return $this->render('viewfromevento', [
            'model' => $this->actionRelacionar($id)
        ]);
    }
    
    private function actionRelacionar($id) {
        /*
        * Obtiene valores de sus tablas relacionadas y se lo asigna al modelo.
        */
        $model = $this->findModel($id);
        $model->nomevento = $model->evento0->nombre .' (' . $model->evento0->codigo .'-'. $model->evento0->edicion .')';
        $model->nomrrpp = $model->rrpp0->nombre .' ' . $model->rrpp0->apellidos;
        return $model;
    }

    /**
     * Creates a new Contratos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        
        $model = new Contratos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    public function actionRrppevento($rrpp)
    {
        /*
        * Muestra un formulario para crear un contrato con el rrpp que recibe como parametro como predeterminado
        */
        $model = new Contratos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['contratos', 'rrpp' => $rrpp, 'nomrrpp' => $model->rrpp0->nombre . " " . $model->rrpp0->apellidos, 'evento' => $model->evento, 'nomevento' => $model->evento0->nombre]);
            }
        } else {
            $model->loadDefaultValues();
            $model->rrpp = $rrpp;
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    public function actionEventorrpp($evento, $nomevento)
    {
        /*
        * Muestra un formulario para crear un contrato con el evento que recibe como parametro como predeterminado
        */
        $model = new Contratos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['rrpps/rrpps', 'evento' => $evento, 'nomevento' => $nomevento]);
            }
        } else {
            $model->loadDefaultValues();
            $model->evento = $evento;
        }

        return $this->render('createfromeventos', [
            'model' => $model,
        ]);
    }
    
    /*Prueba Fallida para crear varios contratos en un mismo formulario- No usar*/
    public function actionInsertar($evento, $rrpps){
        
        $post = Yii::$app->request->post();

        for ($i=0; $i<count($rrpps); $i++){
          $data[$i][0] = $evento;
          $data[$i][1] = $rrpps[$i]; 
        }

        Yii::$app->db->createCommand()->batchInsert('contratos',[
          'evento',
          'rrpp',
        ],
        $data
        )->execute();
        
    }

    /**
     * Updates an existing Contratos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
    
    public function actionUpdatefromeventos($id)
    {
        /*
         * Renderiza una vista con las migas de pan necesarias para que la navegacion sea natural. 
         * Por lo demas es igual que la funcion action update.
         */
        $model = $this->actionRelacionar($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['viewfromevento', 'id' => $model->id]);
        }

        return $this->render('updatefromeventos', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Contratos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    /*No usar*/
    public function actionDeletefromeventos($id, $evento, $nomevento)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['rrpps/rrpps', 'evento' => $evento, 'nomevento' => $nomevento]);
    }
    
    public function actionDeletefromrrpps($id, $rrpp, $nomrrpp)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['contratos', 'rrpp' => $rrpp, 'nomrrpp' => $nomrrpp, 'from'=>'rrpps']);
    }
    /**
     * Finds the Contratos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Contratos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Contratos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    
    public function actionContratos($rrpp) {
       
        /*
        * Muestra todos los eventos en los que esta activo el rrpp que recibe como parametro
        */
        
        $dataProvider = new ActiveDataProvider([
            'query' => Contratos::find()->innerJoinWith("evento0")->innerJoinWith("rrpp0")
                ->where("contratos.rrpp = $rrpp")->
                select(["contratos.id id, contratos.evento evento, eventos.nombre nomevento, eventos.codigo codigo, concat(rrpps.nombre, ' ', rrpps.apellidos)nomrrpp"])
        ]);
        
        return $this->render("contratosrrpp",[
            "dataProvider" => $dataProvider,
        ]);
    }
    
    public function actionIndexevento($evento)
    {
        /*
         * Muestra todos los RRPP que esten contratados en un evento recibido como parametro
         */
        $dataProvider = new ActiveDataProvider([
            'query' => Contratos::find()
                ->innerJoinWith('rrpp0')->innerJoinWith('evento0')
                ->select(['contratos.id id, eventos.nombre nomevento, rrpps.id rrpp, eventos.id evento, concat(rrpps.nombre,rrpps.apellidos) nomrrpp'])
                ->where("contratos.evento = $evento"),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
}

controllers/RrppsController.php
<?php

namespace app\controllers;

use app\models\Rrpps;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RrppsController implements the CRUD actions for Rrpps model.
 */
class RrppsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Rrpps models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Rrpps::find()->where('id <> -1')
                ->select(['id, dni, concat(nombre, " ", apellidos) nombre, telefono, email, '
                    . 'DATE_FORMAT(f_nacimiento, "%d-%m-%Y") f_nacimiento']),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rrpps model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->actionFormatofechas($id),
        ]);
    }
    
    //Dar formato a las fechas
    private function actionFormatofechas($id) {
        /*
         * Devuelve un modelo con las fechas formateadas
         */
        $model = $this->findModel($id);
        $date = new \DateTime($model->f_nacimiento);
        $model->f_nacimiento = $date->format('d/m/Y');
        return $model;
    }
    
    /**
     * Creates a new Rrpps model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Rrpps();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Rrpps model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Rrpps model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rrpps model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Rrpps the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rrpps::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La página solicitada no existe.');
    }
    
    //Obtener todos los rrpps activos en un evento y sus entradas
    public function actionRrpps($evento) {
        
        //Consulta sql para obtener tambien los rrpps que no esten activos en el evento pero tengan entradas de este
        $sql = "select rrpps.id, rrpps.nombre, rrpps.apellidos, entradas.evento evento,count(*) numentradas
            from rrpps 
            inner join entradas on entradas.vendedor = rrpps.id 
            where rrpps.id <> -1 and entradas.evento = $evento
            group by rrpps.id";
        
        //RRPPS dados de alta en el evento pasado como parametro y entradas que tienen asignadas
        $dataProvider = new ActiveDataProvider([
            'query' => Rrpps::find()
                ->innerJoinWith("contratos")
                ->where("rrpps.id <> -1 and contratos.evento = $evento")
                ->select(["rrpps.id, rrpps.nombre, rrpps.apellidos, contratos.evento evento,"
                    . "(select count(*)from entradas where entradas.evento = $evento and entradas.vendedor = rrpps.id) numentradas"])
                ->union($sql)
        ]);
        
        return $this->render("Rrpps",[
            "dataProvider" => $dataProvider,
        ]);
    }
    
}

views/contratos/_contratosrrpp.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
$from = Yii::$app->getRequest()->getQueryParam('from');
/*
 * 
 *      Vista que muestra un evento en el que esta contratado un rrpp
 * 
 */


// Se busca la imagen respectiva y sino se muestra una por defecto
$img = "";
if(file_exists(getcwd().'/img/eventos/'.$model->codigo.'.jpg')){
    $img = Html::img('@web/img/eventos/'.$model->codigo.'.jpg', ['class' => 'imgview']);
} else if(file_exists(getcwd().'/img/eventos/'.$model->codigo.'.png')){
    $img = Html::img('@web/img/eventos/'.$model->codigo.'.png', ['class' => 'imgview']);
} else {
    $img = Html::img('@web/img/eventos/default.jpg', ['class' => 'imgview']);
}
?>
<!-- <?= var_dump($model) ?> -->
<div class="card sombrabox" style="margin-top: 10px; margin-bottom: 20px">
    <div class="card-body">
        <div class="caption text-center">
            <h4><?= $model->nomevento ?></h4>
            <?= $img?>
            <?= Html::a('Ver', ['/contratos/viewfromevento', 'id' => $model->id, 'from'=>$from], ['class' => 'btn btn-lxt sombrabox']) ?>
        </div>

    </div>
</div> 

views/contratos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Contratos */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="contratos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'evento')->dropDownList($model->getdropdownEventos()) ?>
    
    <?= $form->field($model, 'rrpp')->dropDownList($model->getdropdownRrpps()) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-lxt']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/contratos/_form2.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Contratos */
/* @var $form yii\widgets\ActiveForm */

/*
 * 
 *  No usar, usado para pruebas
 *  
 */

?>

<div class="contratos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'evento')->dropDownList($model->getdropdownEventos()) ?>
    <!--<?= $form->field($model, 'rrpp')->dropDownList($model->getdropdownRrpps()) ?>-->   
    
    <?= $form->field($model, 'rrpp')->checkboxList($model->getdropdownRrpps()) ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-lxt']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/contratos/contratosrrpp.php
<?php
use yii\helpers\Html;
use yii\helpers\HTMLPurifier;
use circulon\widgets\ColumnListView;

/*
 * 
 *      Vista que muestra todos los contratos de un RRPP
 * 
 */

// Obtener el id evento, nombre del evento, id de rrpp y nombre de rrpp desde el parametro del controlador
$nomrrpp = Yii::$app->getRequest()->getQueryParam('nomrrpp');
$idrrpp = Yii::$app->getRequest()->getQueryParam('rrpp');
$nomevento = Yii::$app->getRequest()->getQueryParam('nomevento');
$evento = Yii::$app->getRequest()->getQueryParam('evento');
$titulo = "Eventos en los que está activo " . $nomrrpp;
$this->title = $titulo;
$boton ="";

// Migas de pan acordes a la navegacion del usuario
if(Yii::$app->getRequest()->getQueryParam('from') === null){
    $this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
    $this->params['breadcrumbs'][] = ['label' => $nomevento, 'url' => ['eventos/view', 'id' => $evento]];
    $this->params['breadcrumbs'][] = ['label' => 'RRPPS', 'url' => ['rrpps/rrpps', 'evento' => $evento, 'nomevento' => $nomevento]];
    $this->params['breadcrumbs'][] = 'Contratos: ' . $nomrrpp;
    $boton=Html::a('Añadir a evento', ['/contratos/rrppevento', 'rrpp' => $idrrpp], ['class' => 'btn btn-lxt sombrabox']);
} else if(Yii::$app->getRequest()->getQueryParam('from') == "rrpps") {
    $this->params['breadcrumbs'][] = ['label' => 'RRPPS', 'url' => ['rrpps/index']];
    $this->params['breadcrumbs'][] = 'Contratos: ' . $nomrrpp;
    $boton = Html::a('Añadir a evento', ['/contratos/rrppevento', 'rrpp' => $idrrpp, 'from' => 'rrpps'], ['class' => 'btn btn-lxt sombrabox']);
}else {
    $this->params['breadcrumbs'][] = ['label' => 'Contratos', 'url' => ['contratos/index']];
    $this->params['breadcrumbs'][] = 'Contratos: ' . $nomrrpp;
    $boton = "";
}

?>

<div class="well well-sm text-center">
    <h1 style="">
        <?=$titulo?>
    </h1>
</div>

<p> <!-- Crea un contrato con el rrpp que se este mostrando -->
    <?= $boton ?>
</p>

<div class="">
    <?= ColumnListView::widget([ 
        'dataProvider' => $dataProvider,
        'itemView' => '_contratosrrpp',
        'layout'=> "\n{pager}\n{items}",
        'columns' => 2,
    ]);
    ?>
</div>

views/contratos/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Contratos */

$this->title = 'Asignar RRPP a evento';

$from = Yii::$app->getRequest()->getQueryParam('from');
if($from === 'rrpps'){
    $this->params['breadcrumbs'][] = ['label' => 'RRPPS', 'url' => ['rrpps/index']];
    $this->params['breadcrumbs'][] = ['label' => 'Contratos: ' . $model->rrpp0->nombre . ' ' . $model->rrpp0->apellidos, 'url' => ['contratos', 'rrpp' => $model->rrpp,'nomrrpp' => $model->rrpp0->nombre . ' ' . $model->rrpp0->apellidos, 'from'=>$from]];
    $this->params['breadcrumbs'][] = $this->title;
} else {
    $this->params['breadcrumbs'][] = ['label' => 'Contratos', 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
}
?>
<div class="contratos-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/contratos/updatefromeventos.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Contratos */

/*
 * 
 *      Vista para actualizar un contrato desde un evento
 * 
 */

$union = $model->nomevento . ' - ' . $model->nomrrpp;
$this->title = 'Cambiar RRPP de evento: ' . $union;
$from = Yii::$app->getRequest()->getQueryParam('from');
if($from === 'rrpps'){
    $this->params['breadcrumbs'][] = ['label' => 'RRPPS', 'url' => ['rrpps/index']];
    $this->params['breadcrumbs'][] = ['label' => 'Contratos: ' . $model->nomrrpp, 'url' => ['contratos', 'rrpp' => $model->rrpp,'nomrrpp' => $model->nomrrpp, 'from'=>$from]];
    $this->params['breadcrumbs'][] = ['label' => $model->nomevento, 'url' => ['viewfromevento', 'id' => $model->id,'from'=>$from]];
} else if($from === null){
    $this->params['breadcrumbs'][] = ['label' => 'Contratos', 'url' => ['contratos', 'rrpp' => $model->rrpp, 'nomrrpp' => $model->nomrrpp]];
    $this->params['breadcrumbs'][] = ['label' => $union, 'url' => ['viewfromevento', 'id' => $model->id]];
} else {
    $this->params['breadcrumbs'][] = ['label' => 'Contratos', 'url' => ['contratos', 'rrpp' => $model->rrpp, 'nomrrpp' => $model->nomrrpp]];
    $this->params['breadcrumbs'][] = ['label' => $union, 'url' => ['viewfromevento', 'id' => $model->id]];
}
$this->params['breadcrumbs'][] = 'Cambiar';
?>
<div class="contratos-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/contratos/viewfromevento.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Contratos */

/*
 * 
 *      Vista detallada de un contrato desde un evento
 * 
 */
 $this->title = 'Contrato: ' . $model->nomevento . ' (' . $model->nomrrpp . ')';
$from = Yii::$app->getRequest()->getQueryParam('from');
$borrar =Html::a('Borrar', ['deletefromeventos', 'id' => $model->id, 'evento' => $model->evento, 'nomevento' => $model->nomevento], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Estas seguro de querer borrar este registro?',
                'method' => 'post',
            ],
        ]);
if($from === 'rrpps'){
    $this->params['breadcrumbs'][] = ['label' => 'RRPPS', 'url' => ['rrpps/index']];
    $this->params['breadcrumbs'][] = ['label' => 'Contratos: ' . $model->nomrrpp, 'url' => ['contratos', 'rrpp' => $model->rrpp,'nomrrpp' => $model->nomrrpp, 'from'=>$from]];
    $this->params['breadcrumbs'][] = $this->title;
    $borrar =Html::a('Borrar', ['deletefromrrpps', 'id'=>$model->id, 'rrpp' => $model->rrpp, 'nomrrpp' => $model->nomrrpp], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Estas seguro de querer borrar este registro?',
                'method' => 'post',
            ],
        ]);
} else if($from === null){
    $this->params['breadcrumbs'][] = ['label' => 'Contratos', 'url' => ['contratos', 'rrpp' => $model->rrpp, 'nomrrpp' => $model->nomrrpp,'evento'=>$model->evento,'nomevento'=>$model->nomevento]];
    $this->params['breadcrumbs'][] = $this->title;
} else {
    $this->params['breadcrumbs'][] = ['label' => 'Contratos', 'url' => ['contratos', 'rrpp' => $model->rrpp, 'nomrrpp' => $model->nomrrpp,'evento'=>$model->evento,'nomevento'=>$model->nomevento]];
    $this->params['breadcrumbs'][] = $this->title;
}

\yii\web\YiiAsset::register($this);
?>
<div class="contratos-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['updatefromeventos', 'id' => $model->id,'from'=>$from], ['class' => 'btn btn-lxt']) ?>
        <?= $borrar ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'options' => ['class' => 'table table-hover table-responsive-md'],
        'attributes' => [
            //'id',
            //'evento',
            //'rrpp',
            'nomevento',
            'nomrrpp',
        ],
    ]) ?>

</div>