models/Rrpps.php
<?php

namespace app\models;

use Yii;
use borales\extensions\phoneInput\PhoneInputValidator;

/**
 * This is the model class for table "rrpps".
 *
 * @property int $id
 * @property string|null $dni
 * @property string|null $nombre
 * @property string|null $apellidos
 * @property string|null $telefono
 * @property string|null $email
 * @property string|null $f_nacimiento
 *
 * @property Contratos[] $contratos
 * @property Entradas[] $entradas
 * @property Eventos[] $eventos
 * @property Jefes $jefes
 * @property Jefes[] $jefes0
 * @property Rrpps[] $jeves
 * @property Rrpps[] $vendedors
 */
class Rrpps extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    
    /*
     * Variables necesarias para campos de tablas relacionadas y calculados
     */
    public $numentradas;
    public $evento;
    
    public static function tableName()
    {
        return 'rrpps';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        // Fecha de hoy
        $date = new \DateTime();
        // Hace 14 años
        $date->sub(new \DateInterval('P14Y'));
        // Fecha maxima de nacimiento
        $max = $date->format('Y-m-d');
        return [
            [['f_nacimiento'], 'safe'],
            [['f_nacimiento'], 'date', 'format' => 'yyyy-M-d', 'max' => $max, 'tooBig' => 'En base a la ley de protección de menores el RRPP no puede ser menor de 14 años para los eventos enfocados a menores de edad.'],
            //Validar dni
            [['dni'], 'string', 'max' => 9],
            [['dni'], 'match', 'pattern' => '/^[0-9]{8}[A-Z]{1}/i'], //Permite introducir unicamente 8 numeros y una letra
            [['nombre', 'apellidos', 'email'], 'string', 'max' => 80],
            [['nombre','apellidos','f_nacimiento','telefono','dni'], 'required'],
            ['email', 'email'],
            ['email', 'unique', 'targetAttribute' => 'email'],
            [['telefono'], 'string', 'max' => 13],
            [['telefono'], PhoneInputValidator::className(), 'region' => 'ES'], //Validacion de numero de telefono con plugin phone imput validator
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dni' => 'DNI',
            'nombre' => 'Nombre',
            'apellidos' => 'Apellidos',
            'telefono' => 'Teléfono',
            'email' => 'Email',
            'f_nacimiento' => 'Fecha de nacimiento',
            'numentradas' => 'Entradas',
        ];
    }

    /**
     * Gets query for [[Contratos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getContratos()
    {
        return $this->hasMany(Contratos::className(), ['rrpp' => 'id']);
    }

    /**
     * Gets query for [[Entradas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEntradas()
    {
        return $this->hasMany(Entradas::className(), ['vendedor' => 'id']);
    }

    /**
     * Gets query for [[Eventos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEventos()
    {
        return $this->hasMany(Eventos::className(), ['id' => 'evento'])->viaTable('contratos', ['rrpp' => 'id']);
    }

    /**
     * Gets query for [[Jefes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJefes()
    {
        return $this->hasOne(Jefes::className(), ['vendedor' => 'id']);
    }

    /**
     * Gets query for [[Jefes0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJefes0()
    {
        return $this->hasMany(Jefes::className(), ['jefe' => 'id']);
    }

    /**
     * Gets query for [[Jeves]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getJeves()
    {
        return $this->hasMany(Rrpps::className(), ['id' => 'jefe'])->viaTable('jefes', ['vendedor' => 'id']);
    }

    /**
     * Gets query for [[Vendedors]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getVendedors()
    {
        return $this->hasMany(Rrpps::className(), ['id' => 'vendedor'])->viaTable('jefes', ['jefe' => 'id']);
    }
    
}

controllers/EventosController.php
<?php

namespace app\controllers;

use app\models\Eventos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * EventosController implements the CRUD actions for Eventos model.
 */
class EventosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Eventos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Eventos::find()//->orderBy('id desc'),
            /*
            'pagination' => [
                'pageSize' => 50
            ],*/
            ,'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Eventos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Eventos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    /*public function uploadPath() {
        return Url::to('@web/img/');
    }*/
    
    public function upload($fil){
        /*
         * Permite subir una imagen de portada del evento
         */
        $var = 'img/eventos/' . $this->request->bodyParams["Eventos"]["codigo"];
        if ($fil) {
            $this->deleteFile($this->request->bodyParams["Eventos"]["codigo"], '');
            foreach ($fil as $file) {
                $file->saveAs($var .'.'. $file->extension);
            }   
        }
    }
    
    public function uploadHeader($fil) {
        /*
         * Permite subir una imagen de cabecera del evento
         */
        $var = 'img/eventos/' . $this->request->bodyParams["Eventos"]["codigo"]. '-home';
        if ($fil) {
            $this->deleteFile($this->request->bodyParams["Eventos"]["codigo"], '-home');
            foreach ($fil as $file) {
                $file->saveAs($var .'.'. $file->extension);
            }   
        }
    }
    
    public function deleteFile($code, $position) {
        /*
        * No usar (Incompleto) - Borra una imagen recibida como parametro
        */
        $img = getcwd() . '/img/eventos/' . $code;
        if($position != ''){
            $img = $img . $position;
        }
        
        //if(file_exists($img . '.jpg') || fileExists($img . '.png')){
          //unlink(Yii::getAlias('@root') . '/img/eventos/'. $img . '.jpg');
          //unlink($img . '.jpg');
          //unlink($img . '.png');
        //} 
    }

    public function actionCreate()
    {
        $model = new Eventos();
        
        if ($this->request->isPost) {
            // Agrega al modelo los archivos subidos en el formulario
            $model->file = UploadedFile::getInstances($model, 'file');
            $model->filemain = UploadedFile::getInstances($model, 'filemain');
            // Sube los archivos del modelo a web/img/eventos
            $this->upload($model->file, $model->filemain);
            $this->uploadHeader($model->filemain);
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    public function actionCreatebak()
    {
        /*
         * Copia de seguridad de actionCreate
         */
        $model = new Eventos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Eventos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            // Agrega al modelo los archivos subidos en el formulario
            $model->file = UploadedFile::getInstances($model, 'file');
            $model->filemain = UploadedFile::getInstances($model, 'filemain');
            // Sube los archivos del modelo a web/img/eventos
            $this->upload($model->file, $model->filemain);
            $this->uploadHeader($model->filemain);
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Eventos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Eventos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Eventos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function findModel($id)
    {
        if (($model = Eventos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    /*public function actionUpload($id){
        $model = $this->findModel($id);
        if(Yii::$app->request->ispost){
            $model->imagen = UploadedFile::getInstance($model, 'imagen');
            if($model->upload()) {
                return $this->redirect(['view', 'id' => $model->id]);
                $model->up
            }
        }
        return $this->render('upload', ['model' => $model]);
    }*/
    
    public function actionMiseventos()
    {
        /*
        *  Devuelve los eventos en los que este contratado el usuario que esta utilizando el sistema
        */
        $dataProvider = new ActiveDataProvider([
            'query' => Eventos::find()
                //->innerJoinWith('contratos')
                ->leftJoin('contratos', 'contratos.evento = eventos.id')
                //->leftJoin('alquileres', $on = 'eventos.id = alquileres.evento')
                ->select('eventos.id, eventos.codigo, eventos.edicion, eventos.nombre, eventos.tipo')
                ->where("contratos.rrpp = (SELECT IdRRPP FROM User WHERE Id =" . \Yii::$app->user->identity->id .")")
                ,
            
            /*'pagination' => [
                'pageSize' => 50
            ],
            */
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            
        ]);

        return $this->render('miseventos', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
}

controllers/RrppsController.php
<?php

namespace app\controllers;

use app\models\Rrpps;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RrppsController implements the CRUD actions for Rrpps model.
 */
class RrppsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Rrpps models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Rrpps::find()->where('id <> -1')
                ->select(['id, dni, concat(nombre, " ", apellidos) nombre, telefono, email, '
                    . 'DATE_FORMAT(f_nacimiento, "%d-%m-%Y") f_nacimiento']),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rrpps model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->actionFormatofechas($id),
        ]);
    }
    
    //Dar formato a las fechas
    private function actionFormatofechas($id) {
        /*
         * Devuelve un modelo con las fechas formateadas
         */
        $model = $this->findModel($id);
        $date = new \DateTime($model->f_nacimiento);
        $model->f_nacimiento = $date->format('d/m/Y');
        return $model;
    }
    
    /**
     * Creates a new Rrpps model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Rrpps();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Rrpps model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Rrpps model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rrpps model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Rrpps the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rrpps::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La página solicitada no existe.');
    }
    
    //Obtener todos los rrpps activos en un evento y sus entradas
    public function actionRrpps($evento) {
        
        //Consulta sql para obtener tambien los rrpps que no esten activos en el evento pero tengan entradas de este
        $sql = "select rrpps.id, rrpps.nombre, rrpps.apellidos, entradas.evento evento,count(*) numentradas
            from rrpps 
            inner join entradas on entradas.vendedor = rrpps.id 
            where rrpps.id <> -1 and entradas.evento = $evento
            group by rrpps.id";
        
        //RRPPS dados de alta en el evento pasado como parametro y entradas que tienen asignadas
        $dataProvider = new ActiveDataProvider([
            'query' => Rrpps::find()
                ->innerJoinWith("contratos")
                ->where("rrpps.id <> -1 and contratos.evento = $evento")
                ->select(["rrpps.id, rrpps.nombre, rrpps.apellidos, contratos.evento evento,"
                    . "(select count(*)from entradas where entradas.evento = $evento and entradas.vendedor = rrpps.id) numentradas"])
                ->union($sql)
        ]);
        
        return $this->render("Rrpps",[
            "dataProvider" => $dataProvider,
        ]);
    }
    
}

views/rrpps/Rrpps.php
<?php
use yii\helpers\Html;
use yii\helpers\HTMLPurifier;
use circulon\widgets\ColumnListView;

/*
 * 
 *  Vista que muestra los rrpps contratados en un evento
 * 
 */

$name = Yii::$app->getRequest()->getQueryParam('nomevento');
$evento = Yii::$app->getRequest()->getQueryParam('evento');
$titulo = "RRPPS activos en " . $name;
$this->title = $titulo;
$this->params['breadcrumbs'][] = ['label' => 'Eventos', 'url' => ['eventos/index']];
$this->params['breadcrumbs'][] = ['label' => $name, 'url' => ['eventos/view', 'id' => $evento]];
$this->params['breadcrumbs'][] = 'RRPPS';
?>

<div class="well well-sm text-center">
    <h1 style="">
        <?=$titulo?>
    </h1>
</div>

<div>
    <?= Html::a('Asignar RRPPS', ['/contratos/eventorrpp', 'evento' => $evento, 'nomevento' => $name], ['class' => 'btn btn-lxt sombrabox']) ?>
</div>

<div class="">
    <?= ColumnListView::widget([ 
        'dataProvider' => $dataProvider,
        'itemView' => '_Rrpp',
        'layout'=> "\n{pager}\n{items}",
        'columns' => 2,
    ]);
    ?>
</div>

views/rrpps/_Rrpp.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/*
 * 
 *  Vista que muestra un rrpp contratado en un evento y la cantidad de entradas que dispone
 * 
 */

$clave = $model->nombre;
$rrpp = $model->id;
$evento = $model->evento;
// Recibe el nombre del evento desde el parametro del controlador
$nomevento = Yii::$app->getRequest()->getQueryParam('nomevento');
$nomrrpp = $model->nombre . ' ' . $model->apellidos;
?>
<!-- <?= var_dump($model) ?> -->
<div class="card sombrabox" style="margin-top: 10px; margin-bottom: 20px">
    <div class="card-body">
        
        <div class="caption text-center">
            <h4><?= $model->nombre . " " .$model->apellidos?></h4>
            <h6>Total entradas:<br><?= $model->numentradas ?></h6>
            <div class="row text-center rrpps">
                <div class="col-md-6" style="padding-bottom: 10px">
                    <?= Html::a('Entradas', ['/entradas/entradasrrpp', 'rrpp' => $rrpp, 'evento' => $evento, 'nomrrpp' => $nomrrpp,'nomevento' => $nomevento], ['class' => 'btn btn-lxt sombrabox']) ?>
                </div>
                <div class="col-md-6">
                    <?= Html::a('Contratos', ['/contratos/contratos', 'rrpp' => $rrpp, 'nomrrpp' => $nomrrpp, 'evento' => $evento, 'nomevento' => $nomevento], ['class' => 'btn btn-outline-lxt sombrabox']) ?>
                </div>
            </div>
        </div>

    </div>
</div> 

views/rrpps/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use borales\extensions\phoneInput\PhoneInput;

/* @var $this yii\web\View */
/* @var $model app\models\Rrpps */
/* @var $form yii\widgets\ActiveForm */

/*
 * 
 * Formulario para crear o actualizar un RRPP
 * 
 */
?>

<div class="rrpps-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        
        <div class="col-md-8">
            
            <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'apellidos')->textInput(['maxlength' => true]) ?>
            
            <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            
        </div>
        
        <div class="col-md-4">
            <!-- Codigo de pais telefonico por defecto españa -->
            <?=$form->field($model, 'telefono')->widget(PhoneInput::className(), [
                'jsOptions' => ['preferredCountries' => ['es'],]])?>
            
            <?= $form->field($model, 'f_nacimiento')->input('date')?>
            
            <?= $form->field($model, 'dni')->textInput(['maxlength' => true]) ?>
            
        </div>
        
    </div>
    
    <!--<?= $form->field($model, 'telefono')->textInput(['maxlength' => true]) ?>-->

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-lxt']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rrpps/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Rrpps */

$this->title = 'Crear RRPP';
$this->params['breadcrumbs'][] = ['label' => 'Rrpps', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

/*
 * 
 * Vista para crear un RRPP
 * 
 */
?>
<div class="rrpps-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/rrpps/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*
 * 
 * Vista de todos los RRPP dados de alta
 * 
 */

$this->title = 'RRPPS';
$this->params['breadcrumbs'][] = $this->title;

// Se obtiene el rol del usuario registrado para mostrarle sus acciones permitidas
$rol = isset(array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]) ? array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]:'';
$boton = "";
$contrato = [
                'header' => '',
                'content' => function($model) {
                    return "";
                }  
            ];
$actioncolumn = [
                'header' => '',
                'content' => function($model) {
                    return "";
                }  
            ];
            
if($rol == "Admin"){
    // Permisos totales para ver, crear, actualizar y borrar
    $boton = Html::a('Crear nuevo RRPP', ['create'], ['class' => 'btn btn-lxt']);
    $contrato = [
                'header' => '',
                'content' => function($model) {
                    return Html::a('Contratos',['/contratos/contratos','rrpp'=>$model->id, 'nomrrpp'=>$model->nombre, 'from'=>'rrpps'], ['class' => 'btn btn-lxt']);
                }  
            ];
    $actioncolumn = [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ];
} else if($rol == "Jefe"){
    // Solo puede crear y actualizar
    $boton = Html::a('Crear nuevo RRPP', ['create'], ['class' => 'btn btn-lxt']);
    $contrato = [
                'header' => '',
                'content' => function($model) {
                    return Html::a('Contratos',['/contratos/contratos','rrpp'=>$model->id, 'nomrrpp'=>$model->nombre, 'from'=>'rrpps'], ['class' => 'btn btn-lxt']);
                }  
            ];
    $actioncolumn = [
                'header' => '',
                'content' => function($model) {
                    return Html::a('Actualizar',['/rrpps/update','id'=>$model->id,], ['class' => 'btn btn-lxt']);
                }  
            ];
}

?>
<div class="rrpps-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= $boton ?>
    </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'tableOptions' => ['class' => 'table table-hover table-responsive-md'],
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            //'id',
            'nombre',
            'f_nacimiento',
            'dni',
            //'apellidos',
            'email:email',
            'telefono',
            $contrato,
            $actioncolumn,
        ],
    ]); ?>


</div>

views/rrpps/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Rrpps */

/*
 * 
 * Vista para actualizar un RRPP
 * 
 */

$this->title = 'Actualizar RRPP: ' . $model->nombre . ' ' . $model->apellidos;
$this->params['breadcrumbs'][] = ['label' => 'Rrpps', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nombre . ' ' . $model->apellidos, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<div class="rrpps-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/rrpps/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Rrpps */

/*
 * 
 * Vista detallada de un RRPP
 * 
 */
$rol = isset(array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]) ? array_keys(\Yii::$app->authManager->getRolesByUser(\Yii::$app->user->getId()))[0]:'';
$this->title = $model->nombre . ' ' . $model->apellidos;
$this->params['breadcrumbs'][] = ['label' => 'Rrpps', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
$borrar = "";
if($rol == "Admin"){
    $borrar = Html::a('Borrar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Esta seguro de querer borrar este elemento?',
                'method' => 'post',
            ],
        ]);
}
?>
<div class="rrpps-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-lxt']) ?>
        <?= $borrar ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'options' => ['class' => 'table table-hover table-responsive-md'],
        'attributes' => [
            //'id',
            'nombre',
            'apellidos',
            'f_nacimiento',
            'dni',
            'email:email',
            'telefono',
        ],
    ]) ?>

</div>